In [2]:
import torch

# 创建一个 2x3 的零张量
x = torch.zeros(2, 3)
print(x)

# 创建一个 2x3 的随机张量
y = torch.rand(2, 3)
print(y)

# 创建一个从数据中的张量
z = torch.tensor([1.0, 2.0, 3.0])
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8124, 0.5209, 0.6872],
        [0.4427, 0.0313, 0.1979]])
tensor([1., 2., 3.])


In [5]:
# 创建大小为(5, 3)的张量，填充随机数
x = torch.rand(5, 3)

# 创建大小为(5, 3)的张量，填充1
y = torch.ones(5, 3)

# 加法运算
z1 = x + y

# 乘法运算
z2 = x * y

# 创建张量并设置requires_grad=True以跟踪计算
v = torch.tensor([[2.0, 3.0], [4.0, 5.0]], requires_grad=True)

# 更复杂的张量计算
z3 = v * v * 3
out = z3.mean()

# 反向传播
out.backward()

# 打印梯度 d(out)/dx
print(v.grad)

# 现在我们将进行更多计算
v2 = v * 2
v2_norm = v2.norm()
v2_norm.backward()

# 打印梯度
print(v.grad)

tensor([[2., 3.],
        [4., 5.]], requires_grad=True)
tensor(40.5000, grad_fn=<MeanBackward0>)
tensor([[3.0000, 4.5000],
        [6.0000, 7.5000]])
tensor([[3.5443, 5.3165],
        [7.0887, 8.8608]])
